import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeInitializer from "./ThemeInitializer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ThemeInitializer />
      <body className="min-h-full flex flex-col bg-white dark:bg-gray-900 text-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
